// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resilientFetch } from "@/lib/networkRetry";

const normalizeEnv = (value: string | undefined): string =>
  (value ?? "").trim().replace(/^['"]|['"]$/g, "");

const SUPABASE_URL = normalizeEnv(import.meta.env.VITE_SUPABASE_URL).replace(/\/+$/, "");
const SUPABASE_PUBLISHABLE_KEY = normalizeEnv(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (input, init) =>
      resilientFetch(input, init, {
        maxAttempts: 3,
        baseDelayMs: 250,
      }),
  },
});
